version: "3"

services:
  mysql-development:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testapp
      MYSQL_DATABASE: testapp
    ports:
      - "3306:3306"

  admin:
    image: adminer
    ports:
      - "8080:8080"
